version: 1.0.0.{build}

image: Visual Studio 2017

install:
  - ps: .\scripts\updateversion.ps1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

configuration: Release

before_build:
  - msbuild /t:restore Xunit.ScenarioReporting.sln

build:
  project: Xunit.ScenarioReporting.sln
  publish_nuget: true
  verbosity: minimal

test_script:  
  - ps .\scripts\appveyortest.ps1

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key: 
    secure: eWYbP7FRTdq3pqMfcwGvPJv6lxPJpP/uxyMrzAT9YS/rA8OYuw83gJ4Yf8Zt7/5g
  artifact: /.*\.nupkg/
