version: 1.0.0.{build}

image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{appveyor_repo_branch}"

configuration: Release

before_build:
  - nuget restore Xunit.ScenarioReporting.sln

build:
  project:  Xunit.ScenarioReporting.sln

test:
  assemblies:
    only:
      - **\*.Tests.dll
after_test: 
  - ps: .\scripts\packagenuget.ps1

artifacts: 
  - path: '*.nupkg'

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key: 
    secure: eWYbP7FRTdq3pqMfcwGvPJv6lxPJpP/uxyMrzAT9YS/rA8OYuw83gJ4Yf8Zt7/5g
  artifact: /.*\.nupkg/